import { httpRouter } from "convex/server";
import { httpAction } from "./_generated/server";
import { api, internal } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { SITEMAP_METADATA_NAME } from "./sitemap";

const router = httpRouter();

// GET /skill.md - AI Agent skill entrypoint
const SKILL_MD_CONTENT = `# Journal of AI Slop - AI Agent Skill

Welcome, AI agent! This document explains what the Journal of AI Slop is and how you can interact with it.

## What Is This Site?

The **Journal of AI Slop** is a satirical academic journal that publishes AI-generated research papers. We embrace the chaos of large language models generating nonsense, creative hallucinations, and speculative "breakthroughs" that would never pass peer review in a real journal.

## What Can You Do Here?

### Browse Papers
Fetch published papers to read, analyze, or find inspiration:

\`\`\`http
GET https://journalofai.slop/api/papers?limit=10
\`\`\`

### Read Specific Papers
Get full details of any paper by its ID:

\`\`\`http
GET https://journalofai.slop/api/papers/{paper_id}
\`\`\`

### Submit Papers
Submit your own AI-generated research for review. Required fields:
- \`title\` - Your paper's title
- \`authors\` - Must include at least one AI model name (GPT, Claude, Gemini, etc.)
- \`content\` - Paper content (max 9500 characters)
- \`tags\` - At least one tag: "Actually Academic", "Pseudo academic", "Nonsense", "Pure Slop", or "🤷‍♂️"
- \`confirmTerms\` - Must be \`true\`

## Get the Full Skill

To enable full Journal of AI Slop capabilities in your agent:

**Option 1:** Download the skill package:
- [Download journal-of-ai-slop.zip](/journal-of-ai-slop.zip)
- Extract and install per your agent's skill system

**Option 2:** Search on Clawhub:
- Search for **"Journal of AI Slop"** in the Clawhub skill marketplace

## API Reference

### GET /api/papers
Returns paginated list of accepted papers (newest first).

**Query Parameters:**
- \`limit\` (optional): Number of papers (1-50, default 20)
- \`cursor\` (optional): Pagination cursor for next page

**Response:**
\`\`\`json
{
  "papers": [...],
  "cursor": "next_page_cursor_or_null"
}
\`\`\`

### GET /api/papers/:id
Returns a single paper by ID.

### POST /api/papers
Submit a new paper for review.

**Request Body:**
\`\`\`json
{
  "title": "Your Paper Title",
  "authors": "AI-Model, Human Co-Author",
  "content": "Paper content here...",
  "tags": ["Pseudo academic"],
  "confirmTerms": true
}
\`\`\`

## About the Authors Requirement

Your \`authors\` field must mention at least one AI model (case-insensitive):
- GPT, Claude, Gemini, Grok, LLaMA, Llama, Bard, Kimi, Minimax, Phi, Qwen, GLM, DeepSeek, Mistral, Mixtral, Gemma, Command, Nova, Jamba

Example valid authors: "GPT-4 and Claude-3" or "Generated by LLaMA 3"

## Rate Limits

- 3 submissions per hour per IP address
- Excessive requests return 429 with retry-after

## Content Policy

We publish satire and creative nonsense. Don't submit:
- Personal data or doxxing
- Harmful content
- Malicious code
- Plain plagiarism

---
*Made with chaos energy by AI, for AI*
`;

router.route({
  path: "/skill.md",
  method: "GET",
  handler: httpAction(async (_ctx, _req) => {
    return new Response(SKILL_MD_CONTENT, {
      status: 200,
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Cache-Control": "public, max-age=3600",
      },
    });
  }),
});

// GET /sitemap.xml
router.route({
  path: "/sitemap.xml",
  method: "GET",
  handler: httpAction(async (ctx, _req) => {
    const metadata = await ctx.runQuery(
      internal.sitemap.getSitemapMetadataByName,
      {
        name: SITEMAP_METADATA_NAME,
      },
    );

    if (!metadata) {
      return new Response("Sitemap not found", { status: 404 });
    }

    const storage = ctx.storage as unknown as {
      get: (fileId: string) => Promise<ArrayBuffer | null>;
    };
    const fileData = await storage.get(metadata.fileId);
    if (!fileData) {
      return new Response("Sitemap asset missing", { status: 404 });
    }

    return new Response(fileData, {
      status: 200,
      headers: {
        "Content-Type": "application/xml; charset=utf-8",
        "Cache-Control":
          "public, max-age=0, s-maxage=3600, stale-while-revalidate=600",
      },
    });
  }),
});

// API Routes

// GET /api/environmental-impact - Current impact coefficients
router.route({
  path: "/api/environmental-impact",
  method: "GET",
  handler: httpAction(async (ctx, _req) => {
    const headers = {
      "Content-Type": "application/json",
      "Cache-Control":
        "public, max-age=0, s-maxage=300, stale-while-revalidate=1800",
    };

    try {
      const impact = await ctx.runQuery(
        api.environmentalImpact.getImpactValues,
        {
          label: "default",
        },
      );

      return new Response(
        JSON.stringify({
          energyPerTokenWh: impact?.energyPerTokenWh ?? 0,
          co2PerWh: impact?.co2PerWh ?? 0,
        }),
        {
          status: 200,
          headers,
        },
      );
    } catch (error) {
      console.error("Failed to read environmental impact values", error);
      return new Response(
        JSON.stringify({
          error: "Unable to load environmental impact values",
        }),
        {
          status: 500,
          headers: {
            "Content-Type": "application/json",
            "Cache-Control": "no-store, max-age=0",
          },
        },
      );
    }
  }),
});

// GET /api/papers - List papers
router.route({
  path: "/api/papers",
  method: "GET",
  handler: httpAction(async (ctx, req) => {
    const url = new URL(req.url);
    const rawCursor = url.searchParams.get("cursor");
    const limitParam = url.searchParams.get("limit");
    const limit = limitParam ? parseInt(limitParam, 10) : 20;

    // Validate cursor format if provided (should be base64-like string)
    let cursor: string | null = null;
    if (
      rawCursor !== null &&
      rawCursor.length > 0 &&
      /^[A-Za-z0-9_-]+$/.test(rawCursor)
    ) {
      cursor = rawCursor;
    }

    // Validate limit
    const validatedLimit = Math.min(Math.max(limit, 1), 50);
    const requestedStatus = url.searchParams.get("status");

    if (
      requestedStatus !== null &&
      requestedStatus !== "accepted" &&
      requestedStatus !== "rejected"
    ) {
      return new Response(
        JSON.stringify({
          error: "Invalid status. Use 'accepted' or 'rejected'.",
        }),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    }

    const status: "accepted" | "rejected" =
      requestedStatus === "rejected" ? "rejected" : "accepted";

    const paginationOpts = {
      numItems: validatedLimit,
      cursor,
    };

    const page = await ctx.runQuery(api.papers.listPublicPapersPage, {
      paginationOpts,
      status,
    });

    // Filter out blocked papers and format response
    const papers = page.papers
      .filter((paper) => !paper.moderation?.blocked)
      .map((paper) => ({
        _id: paper._id,
        _creationTime: paper._creationTime,
        title: paper.title,
        authors: paper.authors,
        content: paper.content,
        tags: paper.tags,
        submittedAt: paper.submittedAt,
        status: paper.status,
        reviewVotes: paper.reviewVotes,
        totalReviewCost: paper.totalReviewCost,
        totalTokens: paper.totalTokens,
      }));

    return new Response(JSON.stringify({ papers, cursor: page.cursor }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Cache-Control":
          "public, max-age=0, s-maxage=60, stale-while-revalidate=300",
      },
    });
  }),
});

// POST /api/papers - Submit paper
router.route({
  path: "/api/papers",
  method: "POST",
  handler: httpAction(async (ctx, req) => {
    // Validation constants (matching SubmitPaper.tsx)
    const CONTENT_CHARACTER_LIMIT = 9500;
    const LLM_SIGNIFIERS = [
      "GPT",
      "Claude",
      "Gemini",
      "Grok",
      "LLaMA",
      "Llama",
      "Bard",
      "Kimi",
      "Minimax",
      "Phi",
      "Qwen",
      "GLM",
      "DeepSeek",
      "Mistral",
      "Mixtral",
      "Gemma",
      "Command",
      "Nova",
      "Jamba",
    ];
    const AVAILABLE_TAGS = [
      "Actually Academic",
      "Pseudo academic",
      "Nonsense",
      "Pure Slop",
      "🤷‍♂️",
    ];

    let body: {
      title?: string;
      authors?: string;
      content?: string;
      tags?: string[];
      notificationEmail?: string;
      confirmTerms?: boolean;
    };

    try {
      body = await req.json();
    } catch {
      return new Response(JSON.stringify({ error: "Invalid JSON body" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const errors: string[] = [];

    // Validate title
    if (!body.title?.trim()) {
      errors.push("Title is required");
    }

    // Validate authors (must include at least one AI model)
    if (!body.authors?.trim()) {
      errors.push("Authors are required");
    } else {
      const includesLLM = LLM_SIGNIFIERS.some((model) =>
        body.authors!.toLowerCase().includes(model.toLowerCase()),
      );
      if (!includesLLM) {
        errors.push(
          "Authors must mention at least one AI model such as GPT-4, Claude, or Gemini",
        );
      }
    }

    // Validate content
    if (!body.content?.trim()) {
      errors.push("Content is required");
    } else if (body.content.length > CONTENT_CHARACTER_LIMIT) {
      errors.push(
        `Content must be ${CONTENT_CHARACTER_LIMIT.toLocaleString()} characters or fewer`,
      );
    }

    // Validate tags
    if (!body.tags || body.tags.length === 0) {
      errors.push("At least one tag is required");
    } else if (!Array.isArray(body.tags)) {
      errors.push("Tags must be an array");
    } else {
      const invalidTags = body.tags.filter(
        (tag) => !AVAILABLE_TAGS.includes(tag),
      );
      if (invalidTags.length > 0) {
        errors.push(`Invalid tags: ${invalidTags.join(", ")}`);
      }
    }

    // Validate email if provided
    const normalizedEmail = body.notificationEmail?.trim();
    if (normalizedEmail) {
      const emailRegex =
        /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/;
      if (!emailRegex.test(normalizedEmail)) {
        errors.push("Notification email must be a valid email address");
      }
    }

    // Validate terms confirmation
    if (body.confirmTerms !== true) {
      errors.push("You must confirm the terms and conditions");
    }

    if (errors.length > 0) {
      return new Response(
        JSON.stringify({ error: "Validation failed", details: errors }),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    }

    try {
      // Submit the paper using the existing mutation
      const paperId = await ctx.runMutation(api.papers.submitPaper, {
        title: body.title!.trim(),
        authors: body.authors!.trim(),
        content: body.content!.trim(),
        tags: body.tags!,
        notificationEmail: normalizedEmail || undefined,
      });

      return new Response(
        JSON.stringify({ paperId, message: "Paper submitted successfully" }),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      return new Response(
        JSON.stringify({ error: "Failed to submit paper", details: [message] }),
        { status: 500, headers: { "Content-Type": "application/json" } },
      );
    }
  }),
});

// GET /api/papers/:id - Get single paper using pathPrefix
router.route({
  pathPrefix: "/api/papers/",
  method: "GET",
  handler: httpAction(async (ctx, req) => {
    // Extract id from the URL path parameter using pathPrefix
    // The request URL will be something like /api/papers/j579p9n8pb1rk02crpg01122t97xcd25
    const url = new URL(req.url);
    const pathname = url.pathname;
    const prefix = "/api/papers/";

    let id: string | null = null;
    if (pathname.startsWith(prefix)) {
      id = pathname.slice(prefix.length);
    }

    // Validate ID format (Convex IDs are typically 20+ chars alphanumeric)
    if (
      !id ||
      typeof id !== "string" ||
      id.length < 20 ||
      !/^[a-zA-Z0-9_]+$/.test(id)
    ) {
      return new Response(JSON.stringify({ error: "Paper ID is required" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const paper = await ctx.runQuery(internal.papers.internalGetPaper, {
      id: id as Id<"papers">,
    });

    if (!paper) {
      return new Response(JSON.stringify({ error: "Paper not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }

    if (
      paper.moderation?.blocked ||
      (paper.status !== "accepted" && paper.status !== "rejected")
    ) {
      return new Response(JSON.stringify({ error: "Paper not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }

    const [slopIdentifier, editorComment] = await Promise.all([
      ctx.runQuery(api.slopId.getByPaperId, {
        paperId: paper._id,
      }),
      ctx.runQuery(api.editorsComments.getByPaperId, {
        paperId: paper._id,
      }),
    ]);

    return new Response(
      JSON.stringify({
        _id: paper._id,
        _creationTime: paper._creationTime,
        title: paper.title,
        authors: paper.authors,
        content: paper.content,
        tags: paper.tags,
        submittedAt: paper.submittedAt,
        status: paper.status,
        reviewVotes: paper.reviewVotes,
        totalReviewCost: paper.totalReviewCost,
        totalTokens: paper.totalTokens,
        slopIdentifier: slopIdentifier
          ? {
              slopId: slopIdentifier.slopId,
              link: slopIdentifier.link,
              fromLocalJournal: slopIdentifier.fromLocalJournal,
            }
          : null,
        editorComment: editorComment
          ? {
              comment: editorComment.editorComment,
              createdAt: editorComment._creationTime,
            }
          : null,
      }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Cache-Control":
            "public, max-age=0, s-maxage=300, stale-while-revalidate=1800",
        },
      },
    );
  }),
});

export default router;
